Repository christianhelle/apiclientcodegen, pull requests merged in 2024-03, with the labels that each got.

#824 Update Microsoft Kiota to v1.12.0
  README.md
  docs/CLI.md
  docs/Marketplace.md
  docs/Marketplace2022.md
  docs/VisualStudioForMac.md
  src/CLI/ApiClientCodeGen.CLI/Commands/CSharp/KiotaCommand.cs
  src/Core/ApiClientCodeGen.Core.Tests/Installer/DependencyInstallerTests.cs
  src/Core/ApiClientCodeGen.Core/Generators/Kiota/KiotaCodeGenerator.cs
  src/Core/ApiClientCodeGen.Core/Installer/DependencyInstaller.cs
  src/VSIX/ApiClientCodeGen.VSIX.Dev17/VSCommandTable.vsct
  src/VSIX/ApiClientCodeGen.VSIX/VSCommandTable.vsct
  src/VSMac/ApiClientCodeGen.VSMac/Properties/Manifest.addin.xml
Labels: enhancement, dependencies

#825 OpenAPI Generator v7.4.0
  README.md
  docs/CLI.md
  docs/Marketplace.md
  docs/Marketplace2022.md
  docs/VisualStudioForMac.md
  src/CLI/ApiClientCodeGen.CLI/Commands/CSharp/OpenApiCSharpGeneratorCommand.cs
  src/CLI/ApiClientCodeGen.CLI/Commands/OpenApiGeneratorCommand.cs
  src/Core/ApiClientCodeGen.Core/Generators/OpenApi/OpenApiCSharpCodeGenerator.cs
  src/Core/ApiClientCodeGen.Core/Resource.Designer.cs
  src/Core/ApiClientCodeGen.Core/Resource.resx
  src/VSIX/ApiClientCodeGen.VSIX.Dev17/VSCommandTable.vsct
  src/VSIX/ApiClientCodeGen.VSIX/VSCommandTable.vsct
  src/VSMac/ApiClientCodeGen.VSMac/Properties/Manifest.addin.xml
Labels: enhancement, dependencies, .NET

#832 Added kiota version detection and its installation if it's not installed
  src/Core/ApiClientCodeGen.Core.Tests/Installer/DependencyInstallerTests.cs
  src/Core/ApiClientCodeGen.Core/Installer/DependencyInstaller.cs
Labels: enhancement
