Repository christianhelle/apiclientcodegen, pull requests merged in 2024-11, with the labels that each got.

#1033 Update Kiota dependencies to v1.14.0
  src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs
  src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs
  test/GeneratedCode/Kiota/Directory.build.props
Labels: enhancement, dependencies

#1034 Microsoft Kiota v1.20.0
  README.md
  docs/CLI.md
  docs/Marketplace.md
  docs/Marketplace2022.md
  docs/VisualStudioForMac.md
  src/CLI/ApiClientCodeGen.CLI/Commands/CSharp/KiotaCommand.cs
  src/Core/ApiClientCodeGen.Core.Tests/Installer/DependencyInstallerTests.cs
  src/Core/ApiClientCodeGen.Core/Generators/Kiota/KiotaCodeGenerator.cs
  src/Core/ApiClientCodeGen.Core/Installer/DependencyInstaller.cs
  src/VSIX/ApiClientCodeGen.VSIX.Dev17/VSCommandTable.vsct
  src/VSIX/ApiClientCodeGen.VSIX/VSCommandTable.vsct
  src/VSMac/ApiClientCodeGen.VSMac/Properties/Manifest.addin.xml
Labels: enhancement, dependencies, .NET

#1040 Update AutoRestArgumentProvider.cs
  src/Core/ApiClientCodeGen.Core/Generators/AutoRest/AutoRestArgumentProvider.cs
Labels: .NET

#1041 Update Microsoft Kiota dependencies to v1.15.2
  src/Core/ApiClientCodeGen.Core/NuGet/PackageDependencies.cs
  src/Core/ApiClientCodeGen.Tests.Common/Build/Projects/KiotaProjectFileContents.cs
  test/GeneratedCode/Kiota/Directory.build.props
Labels: dependencies, .NET

#1044 OpenAPI Generator v7.10.0
  README.md
  docs/CLI.md
  docs/Marketplace.md
  docs/Marketplace2022.md
  docs/VisualStudioForMac.md
  src/CLI/ApiClientCodeGen.CLI/Commands/CSharp/OpenApiCSharpGeneratorCommand.cs
  src/CLI/ApiClientCodeGen.CLI/Commands/OpenApiGeneratorCommand.cs
  src/Core/ApiClientCodeGen.Core/Generators/OpenApi/OpenApiCSharpCodeGenerator.cs
  src/Core/ApiClientCodeGen.Core/Resource.Designer.cs
  src/Core/ApiClientCodeGen.Core/Resource.resx
  src/VSIX/ApiClientCodeGen.VSIX.Dev17/VSCommandTable.vsct
  src/VSIX/ApiClientCodeGen.VSIX/VSCommandTable.vsct
  src/VSMac/ApiClientCodeGen.VSMac/Properties/Manifest.addin.xml
Labels: enhancement, dependencies, .NET

#1045 Update MacOS runner
  .github/workflows/production-tests.yml
  .github/workflows/regression-tests.yml
  .github/workflows/release.yml
  .github/workflows/smoke-tests.yml
  .github/workflows/unit-tests.yml
  .github/workflows/vsmac.yml
Labels: dependencies

#1051 NSwag v14.2.0
  README.md
  docs/CLI.md
  docs/Marketplace.md
  docs/Marketplace2022.md
  docs/VisualStudioForMac.md
  src/CLI/ApiClientCodeGen.CLI/Commands/CSharp/NswagCommand.cs
  src/Core/ApiClientCodeGen.Core/Generators/NSwag/NSwagCSharpCodeGenerator.cs
  src/VSIX/ApiClientCodeGen.VSIX.Dev17/VSCommandTable.vsct
  src/VSIX/ApiClientCodeGen.VSIX/VSCommandTable.vsct
  src/VSMac/ApiClientCodeGen.VSMac/Properties/Manifest.addin.xml
Labels: enhancement, dependencies, .NET
